### ISSUE TITLE
Roadmap for supporting different frameworks

### ISSUE THREAD

**Issue by typhoonzero** [elasticdeeplearning/edl#36]
- [ ] design doc of implementing generic python API tools to enable fault tolerant. Developers can insert some lines of code in their training program to enable fault tolerant training -- 2 week with a discussion
- [ ] implement this generic python API available for at least 1 framework. -- 2 weeks
- [ ] polish CRD implementation, and run test on real clusters. -- 2 weeks
- [ ] implement and test for more frameworks: Tensorflow, Keras, Caffe2 -- 4 weeks
